[context.production.environment]
  REACT_APP_CHAIN_ID = "1"
  NETLIFY_USE_YARN = "true"
  REACT_APP_ENABLE_HISTORY = "true"
  REACT_APP_INFURA_PROJECT_ID="225fb67024db4200bfdd1588919649f5"
  REACT_APP_ETHERSCAN_API_KEY="5BGRCTVMT8V28A9X5TJX3FIYZNIXJVGACA"
  REACT_APP_MAINNET_JSONRPC = "https://eth-mainnet.g.alchemy.com/v2/phgTY_b6J55iqtkq9r6iifxv-cJViAHb"
  REACT_APP_MAINNET_WSRPC = "wss://eth-mainnet.g.alchemy.com/v2/phgTY_b6J55iqtkq9r6iifxv-cJViAHb"
  
[context."staging".environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[context."master".environment]
  REACT_APP_CHAIN_ID = "1"
  NETLIFY_USE_YARN = "true"
  REACT_APP_ENABLE_HISTORY = "true"
  REACT_APP_INFURA_PROJECT_ID="225fb67024db4200bfdd1588919649f5"
  REACT_APP_ETHERSCAN_API_KEY="5BGRCTVMT8V28A9X5TJX3FIYZNIXJVGACA"
  REACT_APP_MAINNET_JSONRPC = "https://eth-mainnet.g.alchemy.com/v2/phgTY_b6J55iqtkq9r6iifxv-cJViAHb"
  REACT_APP_MAINNET_WSRPC = "wss://eth-mainnet.g.alchemy.com/v2/phgTY_b6J55iqtkq9r6iifxv-cJViAHb"
  
[context.deploy-preview.environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[functions]
  directory = "packages/nounsbr-webapp/functions"

[build]
  command = "git submodule update --init --recursive --depth=1 && yarn workspace @nounsbr/webapp build"
  publish = "packages/nounsbr-webapp/build"
